### ISSUE TITLE
Task Pending, Possible interference with disnake task loops

### ISSUE THREAD

**Issue by scosco97** [mathsman5133/coc.py#127] opened 2022-10-13 15:08 UTC
This is the traceback that I receive. Basically, any function that uses `async for x in clan.get_detailed_members():`. Any other loops/functions works just fine, or so it seems to me.
![image](https://user-images.githubusercontent.com/63084584/195634536-e7d61d50-bcd7-487e-ab36-b9006ad715b9.png)

**Comment by doluk** [comment] 2023-01-27 18:19
I am not able to reproduce this. @scosco97 could you check if the issue still persists with the newest version of coc.py and the updated login method (`await coc_client.login()` instead of `coc.login()`?

**Comment by doluk** [comment] 2023-01-27 22:16
Not reproducible on the current master branch, so we close this for now

**Closed by doluk** 2023-01-27 22:16 UTC
Labels: question
